-- Change color of hover window
-- vim.cmd [[autocmd! ColorScheme * highlight NormalFloat bg=#2b3339 guibg=#2b3339]]
-- vim.cmd [[autocmd! ColorScheme * highlight FloatBorder guifg=#d3c6aa guibg=#2b3339]]
-- vim.lsp.handlers['textDocument/hover'] = vim.lsp.with(vim.lsp.handlers.hover, {
--   border = 'round',
-- })
